from pathlib import Path
import json

import numpy as np
import pandas as pd


# ==========================================================
# RIDEGUARDIAN
# RIDER BEHAVIOUR - SEQUENCE DATASET PREPARATION
# ==========================================================

BASE_DIR = Path(r"C:\RIDER_SYSTEM\RideGuardian")

INPUT_FILE = (
    BASE_DIR
    / "ai"
    / "datasets"
    / "rides"
    / "processed"
    / "ride_readings_processed_with_split.csv"
)

OUTPUT_DIR = (
    BASE_DIR
    / "ai"
    / "datasets"
    / "rides"
    / "sequences"
)

OUTPUT_DIR.mkdir(
    parents=True,
    exist_ok=True
)


# ==========================================================
# SETTINGS
# ==========================================================

SEQUENCE_LENGTH = 30
STRIDE = 10


# ==========================================================
# SENSOR FEATURES
# ==========================================================
#
# These are the actual sensor inputs.
#
# IMPORTANT:
# We deliberately DO NOT use:
#
# rideSafetyScore
# rideRiskPercentage
# speedRisk
# hardBraking
# hardAcceleration
# suddenTurn
# eventType
#
# as model inputs.
#
# Those are outputs/derived safety information.
# ==========================================================

FEATURE_COLUMNS = [

    "speedKmh",

    "accelerationX",
    "accelerationY",
    "accelerationZ",

    "gyroX",
    "gyroY",
    "gyroZ",

    "timeSincePreviousReadingSec",

]


# ==========================================================
# ACTUAL TARGET COLUMN
# ==========================================================
#
# Your processed CSV uses rideSafetyScore.
#
# This is the current rule-based score generated by
# RideGuardian and is used ONLY as the target.
# ==========================================================

TARGET_COLUMN = "rideSafetyScore"


# ==========================================================
# SPLIT COLUMN
# ==========================================================

SPLIT_COLUMN = "split"


# ==========================================================
# LABEL MAPPING
# ==========================================================

LABEL_MAP = {
    "SAFE": 0,
    "MODERATE": 1,
    "RISKY": 2,
}


def safety_label(score):

    if pd.isna(score):
        return "UNKNOWN"

    score = float(score)

    if score >= 80:
        return "SAFE"

    if score >= 60:
        return "MODERATE"

    return "RISKY"


# ==========================================================
# START
# ==========================================================

print("=" * 70)
print("RIDEGUARDIAN RIDER BEHAVIOUR")
print("SEQUENCE DATASET PREPARATION")
print("=" * 70)

print()

print("Input:")
print(INPUT_FILE)

print()


# ==========================================================
# CHECK INPUT
# ==========================================================

if not INPUT_FILE.exists():

    raise FileNotFoundError(
        f"""
Input dataset not found:

{INPUT_FILE}

Make sure this file exists:

ai\\datasets\\rides\\processed\\
ride_readings_processed_with_split.csv
"""
    )


# ==========================================================
# LOAD CSV
# ==========================================================

df = pd.read_csv(
    INPUT_FILE
)


print(
    "Rows loaded:",
    len(df)
)

print(
    "Columns:",
    len(df.columns)
)


# ==========================================================
# SHOW COLUMNS
# ==========================================================

print()
print("Available columns:")

for column in df.columns:

    print(
        "  -",
        column
    )


# ==========================================================
# REQUIRED COLUMNS
# ==========================================================

REQUIRED_COLUMNS = [

    "rideId",

    "timestamp",

    SPLIT_COLUMN,

    TARGET_COLUMN,

] + FEATURE_COLUMNS


missing = [

    column

    for column in REQUIRED_COLUMNS

    if column not in df.columns

]


if missing:

    print()
    print("=" * 70)
    print("DATASET COLUMN ERROR")
    print("=" * 70)

    print()

    print(
        "Missing columns:"
    )

    for column in missing:

        print(
            "  -",
            column
        )

    print()

    print(
        "The CSV was NOT modified."
    )

    raise ValueError(
        "Required columns are missing."
    )


# ==========================================================
# TIMESTAMP
# ==========================================================

df["timestamp"] = pd.to_datetime(

    df["timestamp"],

    errors="coerce",

    utc=True,

)


# ==========================================================
# NUMERIC CONVERSION
# ==========================================================

for column in FEATURE_COLUMNS:

    df[column] = pd.to_numeric(

        df[column],

        errors="coerce",

    )


df["rideId"] = pd.to_numeric(

    df["rideId"],

    errors="coerce",

)


df[TARGET_COLUMN] = pd.to_numeric(

    df[TARGET_COLUMN],

    errors="coerce",

)


# ==========================================================
# REMOVE INVALID RIDE IDs
# ==========================================================

df = df[
    df["rideId"].notna()
].copy()


df["rideId"] = df[
    "rideId"
].astype(int)


# ==========================================================
# CREATE TARGET LABEL
# ==========================================================

df["targetLabel"] = df[
    TARGET_COLUMN
].apply(
    safety_label
)


# ==========================================================
# DISPLAY TARGET DISTRIBUTION
# ==========================================================

print()
print("=" * 70)
print("TARGET DISTRIBUTION")
print("=" * 70)

print()

print(
    df[
        ["rideId", TARGET_COLUMN, "targetLabel"]
    ]
    .drop_duplicates(
        subset=["rideId"]
    )
    .sort_values("rideId")
    .to_string(index=False)
)


# ==========================================================
# SORT
# ==========================================================

df = df.sort_values(

    [
        "rideId",
        "timestamp",
    ],

    kind="stable",

).reset_index(
    drop=True
)


# ==========================================================
# STORAGE
# ==========================================================

all_sequences = {

    "train": [],

    "val": [],

    "test": [],

}


all_labels = {

    "train": [],

    "val": [],

    "test": [],

}


all_ride_ids = {

    "train": [],

    "val": [],

    "test": [],

}


all_start_indices = {

    "train": [],

    "val": [],

    "test": [],

}


manifest_rows = []


# ==========================================================
# CREATE SEQUENCES
# ==========================================================

print()
print("=" * 70)
print("CREATING SEQUENCES")
print("=" * 70)

print()


for ride_id, ride_df in df.groupby(

    "rideId",

    sort=True,

):

    ride_df = ride_df.sort_values(

        "timestamp",

        kind="stable",

    ).reset_index(
        drop=True
    )


    # ------------------------------------------------------
    # SPLIT
    # ------------------------------------------------------

    split_values = (

        ride_df[SPLIT_COLUMN]

        .dropna()

        .astype(str)

        .str.lower()

        .unique()

    )


    if len(split_values) == 0:

        print(
            f"Ride {ride_id}: "
            "NO SPLIT - skipped"
        )

        continue


    split = split_values[0]


    if split not in all_sequences:

        print(
            f"Ride {ride_id}: "
            f"invalid split '{split}' - skipped"
        )

        continue


    # ------------------------------------------------------
    # SAFETY SCORE
    # ------------------------------------------------------

    scores = ride_df[
        TARGET_COLUMN
    ].dropna()


    if len(scores) == 0:

        print(
            f"Ride {ride_id}: "
            "NO SAFETY SCORE - skipped"
        )

        continue


    ride_score = float(
        scores.iloc[0]
    )


    label = safety_label(
        ride_score
    )


    if label == "UNKNOWN":

        print(
            f"Ride {ride_id}: "
            "UNKNOWN LABEL - skipped"
        )

        continue


    # ------------------------------------------------------
    # LENGTH CHECK
    # ------------------------------------------------------

    reading_count = len(
        ride_df
    )


    if reading_count < SEQUENCE_LENGTH:

        print(

            f"Ride {ride_id}: "

            f"{reading_count} readings "

            f"< {SEQUENCE_LENGTH} "

            "required - skipped"

        )

        continue


    # ------------------------------------------------------
    # SLIDING WINDOWS
    # ------------------------------------------------------

    sequence_count = 0


    for start in range(

        0,

        reading_count
        - SEQUENCE_LENGTH
        + 1,

        STRIDE,

    ):

        end = (
            start
            + SEQUENCE_LENGTH
        )


        window = ride_df.iloc[
            start:end
        ]


        # --------------------------------------------------
        # GET SENSOR DATA
        # --------------------------------------------------

        sequence_df = window[
            FEATURE_COLUMNS
        ].copy()


        # --------------------------------------------------
        # HANDLE MISSING VALUES
        # --------------------------------------------------
        #
        # The first reading can legitimately have no
        # previous-reading time value.
        #
        # We interpolate within the sequence.
        #
        # Remaining impossible values become zero.
        # --------------------------------------------------

        sequence_df = (

            sequence_df

            .interpolate(

                method="linear",

                limit_direction="both",

            )

        )


        sequence_df = (

            sequence_df

            .fillna(0)

        )


        sequence = sequence_df.to_numpy(

            dtype=np.float32

        )


        # --------------------------------------------------
        # STORE
        # --------------------------------------------------

        all_sequences[
            split
        ].append(
            sequence
        )


        all_labels[
            split
        ].append(
            label
        )


        all_ride_ids[
            split
        ].append(
            ride_id
        )


        all_start_indices[
            split
        ].append(
            start
        )


        # --------------------------------------------------
        # MANIFEST
        # --------------------------------------------------

        manifest_rows.append({

            "split":
                split,

            "rideId":
                ride_id,

            "sequenceIndex":
                sequence_count,

            "startReading":
                start,

            "endReading":
                end - 1,

            "sequenceLength":
                SEQUENCE_LENGTH,

            "safetyScore":
                ride_score,

            "targetLabel":
                label,

        })


        sequence_count += 1


    print(

        f"Ride {ride_id}: "

        f"{reading_count} readings → "

        f"{sequence_count} sequences → "

        f"{label}"

    )


# ==========================================================
# SAVE NPZ
# ==========================================================

print()
print("=" * 70)
print("SAVING SEQUENCE DATASETS")
print("=" * 70)


for split in [

    "train",

    "val",

    "test",

]:

    sequences = all_sequences[
        split
    ]


    labels = all_labels[
        split
    ]


    if len(sequences) == 0:

        print()

        print(
            f"{split.upper()}: "
            "NO SEQUENCES"
        )

        continue


    X = np.stack(
        sequences
    ).astype(
        np.float32
    )


    y = np.array(

        [
            LABEL_MAP[label]

            for label in labels

        ],

        dtype=np.int64,

    )


    ride_ids = np.array(

        all_ride_ids[split],

        dtype=np.int64,

    )


    start_indices = np.array(

        all_start_indices[split],

        dtype=np.int64,

    )


    output_file = (

        OUTPUT_DIR

        / f"{split}.npz"

    )


    np.savez_compressed(

        output_file,

        X=X,

        y=y,

        ride_ids=ride_ids,

        start_indices=start_indices,

    )


    print()

    print(
        f"{split.upper()}"
    )

    print(
        "Sequences:",
        len(X)
    )

    print(
        "Shape:",
        X.shape
    )

    print(
        "Labels:"
    )

    for label, number in LABEL_MAP.items():

        count = labels.count(
            label
        )

        print(
            f"  {label}: {count}"
        )


    print(
        "Saved:",
        output_file
    )


# ==========================================================
# MANIFEST
# ==========================================================

manifest = pd.DataFrame(
    manifest_rows
)


manifest_path = (

    OUTPUT_DIR

    / "sequence_manifest.csv"

)


manifest.to_csv(

    manifest_path,

    index=False,

)


# ==========================================================
# SEQUENCE INFORMATION
# ==========================================================

sequence_info = {

    "sequenceLength":
        SEQUENCE_LENGTH,

    "stride":
        STRIDE,

    "features":
        FEATURE_COLUMNS,

    "featureCount":
        len(FEATURE_COLUMNS),

    "targetColumn":
        TARGET_COLUMN,

    "labels":
        LABEL_MAP,

    "inputFile":
        str(INPUT_FILE),

    "outputDirectory":
        str(OUTPUT_DIR),

    "rawDataModified":
        False,

}


info_path = (

    OUTPUT_DIR

    / "sequence_info.json"

)


info_path.write_text(

    json.dumps(

        sequence_info,

        indent=2,

    ),

    encoding="utf-8",

)


# ==========================================================
# FINAL SUMMARY
# ==========================================================

print()
print("=" * 70)
print("SEQUENCE DATASET COMPLETE")
print("=" * 70)

print()

print(
    "Train sequences:",
    len(
        all_sequences["train"]
    )
)

print(
    "Validation sequences:",
    len(
        all_sequences["val"]
    )
)

print(
    "Test sequences:",
    len(
        all_sequences["test"]
    )
)

print()

print(
    "Sequence length:",
    SEQUENCE_LENGTH
)

print(
    "Stride:",
    STRIDE
)

print(
    "Sensor features:",
    len(FEATURE_COLUMNS)
)

print()

print(
    "Target:",
    TARGET_COLUMN
)

print()

print(
    "Output:"
)

print(
    OUTPUT_DIR
)

print()

print(
    "Manifest:"
)

print(
    manifest_path
)

print()

print("=" * 70)
print("RAW CSV WAS NOT MODIFIED")
print("=" * 70)